-- 코드를 작성해주세요
SELECT DISTINCT DEVELOPERS.ID,DEVELOPERS.EMAIL,DEVELOPERS.FIRST_NAME, DEVELOPERS.LAST_NAME 
FROM DEVELOPERS
JOIN SKILLCODES
ON (DEVELOPERS.SKILL_CODE & SKILLCODES.CODE) = SKILLCODES.CODE
WHERE SKILLCODES.CATEGORY IN ("Front End")
ORDER BY DEVELOPERS.ID ASC;